### ISSUE TITLE
Stuck at "Loading Airport Data..."

### ISSUE THREAD

**Issue by cayers71** [nigel-daniels/MMM-FAA-Delay#1]
Module was working yesterday, not sure what happened.

MM app returns the following:

Whoops! There was an uncaught exception...
TypeError: Cannot read property 'Weather' of undefined
    at Request._callback (/home/odroid/MagicMirror-master/modules/MMM-FAA-Delay/node_helper.js:78:57)
    at Request.self.callback (/home/odroid/MagicMirror-master/modules/MMM-FAA-Delay/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/odroid/MagicMirror-master/modules/MMM-FAA-Delay/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/odroid/MagicMirror-master/modules/MMM-FAA-Delay/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by nigel-daniels** [comment]
Sorry for the insanely long delay in fixing this!  A full time job has clobbered my home project time.
